language: python
dist: xenial

matrix:
    include:
        - python: 2.6
          env:
              - TOXENV=py26
              - PIP_DEPS="virtualenv<16.0 tox<3.0"
        - python: 2.7
          env:
              - TOXENV=py27
              - PIP_DEPS="tox"
        - python: 3.3
          env:
              - TOXENV=py33
              - PIP_DEPS="virtualenv<16.0 tox<3.0"
        - python: 3.4
          env:
              - TOXENV=py34
              - PIP_DEPS="tox"
        - python: 3.6
          env:
              - TOXENV=py36
              - PIP_DEPS="tox"

install:
- pip install $PIP_DEPS

script:
- tox
